### ISSUE TITLE
[Enhancement] keep model value with the raw value

### ISSUE THREAD

**Issue by eduardodgarciac** [TobyMosque/app-extension-qdecimal#2]
When using ',' as decimal separator, could be good if the model can keep '.' as decimal separator because 1,1 is not a number in javascript, you have to handle it as string. Something like the existing "unmasked-value" prop.

**Comment by TobyMosque** [comment]
![image](https://user-images.githubusercontent.com/13981214/63530201-5f2acb00-c4dc-11e9-9c5e-b528c894cb48.png)
QDecimal value must be a number, internally the component will parses that to a string before display it, and will parsed back when occurs a input event.

**Comment by eduardodgarciac** [comment]
Checking again, I noticed the error occurs using rules.

If you add a rule like `:rules="[v => v > 0 || 'error']"` will throw an error because is comparing against a string.

For example, this is my case. `<q-decimal lang="es" :places="10" :precision="3" :step="1" label="N°" :rules="[v => v > 0 || 'error']" v-model="n"/>`

**Comment by TobyMosque** [comment]
do you can update to beta.0 and try again?
![image](https://user-images.githubusercontent.com/13981214/63537140-7624e980-c4eb-11e9-9cbc-b30e44fc8143.png)

**Comment by eduardodgarciac** [comment]
Now is working, thank you!!
